name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      ssh:
        image: rastasheep/ubuntu-sshd:18.04
        ports:
          - 2222:22

    strategy:
      matrix:
        php: [8.4, 8.3, 8.2]

    name: PHP${{ matrix.php }}

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: ssh2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: |
        composer install --no-progress --prefer-dist --no-interaction

    - name: Run test phpunit
      run: composer test
